version: '3.1'

services:
  app:
    build: .
    command: wait-for mongo:27017 -t 40 -- ./start.sh
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    environment:
      DB_USER: $DB_USER
      DB_PASS: $DB_PASS
      DB_NAME: $DB_NAME
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
      PORT: 3000
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME:  $DB_USER
      MONGO_INITDB_ROOT_PASSWORD: $DB_PASS
    volumes:
      - /dbData:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME:  $DB_USER
      ME_CONFIG_MONGODB_ADMINPASSWORD: $DB_PASS
      ME_CONFIG_MONGODB_URL: mongodb://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/

# Anotações     
#container é passageiro === efêmero